### ISSUE TITLE
Support authentication via OIDC

### ISSUE THREAD

**Issue by kmandal-volvo** [eshepelyuk/apicurio-registry-helm#1]
Helm chart deployment workes fine with persistency. Now I need to connect Apicurio CLI and API using OIDC ( Curity ) need helm chart configuration for that implementation.

**Comment by eshepelyuk** [comment]
This feature is on the roadmap. There are 2 alternatives at the moment

* intertnal keycloak integration ,hat might now work with other oidc providers
* Adoption of OAuth2Proxy that has a wider range of supported providers

I consider 2nd option is more preferable since it can bring a better integration with different OIDC providers.

So, contribution are welcome.

**Comment by kmandal-volvo** [comment]
internal keycloak integration,that might now work with other OIDC providers - There is not value option is available in the helm chart in https://github.com/eshepelyuk/apicurio-registry-helm

**Comment by eshepelyuk** [comment]
You may try to configure it via env variables 

1. https://www.apicur.io/registry/docs/apicurio-registry/2.0.1.Final/getting-started/assembly-configuring-the-registry.html#registry-security
1. https://github.com/eshepelyuk/apicurio-registry-helm/blob/main/values.yaml#L19

**Comment by kmandal-volvo** [comment]
registry: - registry: Additional property extraEnv is not allowed after adding 
```
  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry"
    tag: "2.0.0.Final"
 # list of name, value pairs of extra environment vars
  extraEnv: 
    auth_enabled: true
    keycloak_url: 
    keycloak_realm: 
    keycloak_api_client_id: apicurio-registry
    keycloak_ui_client_id: registry-api
```

**Comment by eshepelyuk** [comment]
@kmandal-volvo 

1. you're using incorrect names for the env vars. you must follow [the manual](https://www.apicur.io/registry/docs/apicurio-registry/2.0.1.Final/getting-started/assembly-configuring-the-registry.html#registry-security)
2. then, please use following name / value pattern to declare in helm values

```yaml
extraEnv: 
  - name: MY_VAR1
    value: MY_VAL1
  - name: MY_VAR2
    value: MY_VAL2
```

**Comment by kmandal-volvo** [comment]
You are correct it's my bad after you close the case I check in my other configuration found the declared patter. Please close the code thanks for info.

**Comment by eshepelyuk** [comment]
Hello @kmandal-volvo 
Does it work for you ? Please let me know, so I would add it to the documentation.

**Comment by kmandal-volvo** [comment]
Added property extraEnv like below now deployment is successful but while launching console or apis it is not asking OIDC authentication. All the property key value-added in the small letter as camel case it is giving issue while deployment though in the documentation it gives Camel case.
```
  image:
    registry: "quay.io"
    repository: "apicurio/apicurio-registry"
    tag: "2.0.1.Final"
 # list of name, value pairs of extra environment vars
  extraEnv:
       - name: "auth_enabled"
         value:  "true"        
       - name: "keycloak_url"
         value: "https://sso.api.xxxx/auth/realms/xxxxx/protocol/openid-connect/token"     
       - name: "keycloak_realm"
         value: "xxxxxxxx"     
       - name: "keycloak_api_client_id"
         value: "apicurio-registry"     
       - name: "keycloak_ui_client_id"
         value: "registry-api"          
```

**Comment by ievgenii-shepeliuk** [comment]
@kmandal-volvo 

why do you still not follow [THE MANUAL](https://www.apicur.io/registry/docs/apicurio-registry/2.0.1.Final/getting-started/assembly-configuring-the-registry.html#registry-security) why naming env variables ?|

![image](https://user-images.githubusercontent.com/86224637/126973844-f631d0ea-2ffa-4b41-abda-913b31d19a32.png)

**Comment by kmandal-volvo** [comment]
Yes first I followed the same way that is defined in the manual but the registry pod is crashing with an issue given below

2021-07-26 10:34:25,296 INFO  [org.apa.kaf.con.jso.JsonConverterConfig] (main) JsonConverterConfig values: 
	converter.type = key
	decimal.format = BASE64
	schemas.cache.size = 0
	schemas.enable = true

2021-07-26 10:34:26,560 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): io.vertx.core.impl.NoStackTraceThrowable: Not Found




```
  extraEnv:
       - name: "AUTH_ENABLED"
         value:  "true"        
       - name: "KEYCLOAK_URL"
         value: "https://sso.api.xxxx/auth/realms/xxxxx/protocol/openid-connect/token"     
       - name: "KEYCLOAK_REALM"
         value: "xxxxx"     
       - name: "KEYCLOAK_API_CLIENT_ID"
         value: "apicurio-registry"     
       - name: "KEYCLOAK_UI_CLIENT_ID"
         value: "registry-api"      
```
